ci: Update check_results to also verify results_verification
The CI will also verify if the results files in the PR fulfill
a set of given requirements

Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>

diff --git a/.github/workflows/check_results.yml b/.github/workflows/check_results.yml
--- a/.github/workflows/check_results.yml
+++ b/.github/workflows/check_results.yml
@@ -49,6 +49,19 @@ jobs:
             exit 1
           fi
           if [[ ${file} == results/* ]]; then
+            echo "Verifying content of ${file}"
+            fd=$(dirname $file)
+            v=$(basename $fd)
+            python3 scripts/results_verification.py -Z ${v} -P ./${file} -E 50 -F 50 -S 5
+            if [ $? -eq 0 ]
+            then
+              echo "Results file succesfully verified"
+            else
+              echo "Results file verification failed"
+              exit 1
+            fi
+          fi
+          if [[ ${file} == results/* ]]; then
             echo "Checking ${file}"
             ~/.local/bin/junit2html --summary-matrix ${file}
           fi
